// This is going to be the javascript that goes hand in hand with facebook.php... 

console.log("this file is being called right now");

// this page is going to allow the user to post what courses he intends on taking...
// make own page with that provides inputs and searches the courses through the ubc website...
// lets just have hard inputs right now...




